library:
  source-dirs: 
  - src
tests:
  hello-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello
copyright: 2018 Author name here
maintainer: nanlan2017
dependencies:
- filepath
- regex-posix
- mtl
- parsec
- containers
- base >= 4.7 && < 5
- bytestring
- directory
- random
- old-time
- array
name: hello
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/hello
license: BSD3
executables:
  hello-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello
description: Please see the README on GitHub at <https://github.com/githubuser/hello#readme>
