library:
  source-dirs: src
tests:
  hello-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- containers
- base >= 4.7 && < 5
- parsec
name: hello
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/hello
license: BSD3
executables:
  hello-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello
description: Please see the README on GitHub at <https://github.com/githubuser/hello#readme>
